pages/login.html

formatted code

---

custom-pages/login/src/services/AuthApi.js

https://nicedigital.atlassian.net/browse/IDAM-235

IDAM-235 Reset password

---

custom-pages/clients/Identity API.json
custom-pages/grants/Identity API.json
custom-pages/resource-servers/Identity API.json
custom-pages/rules/Force email verification.js

https://nicedigital.atlassian.net/browse/IDAM-246

IDAM-246 Using authorise attribute

---

custom-pages/database-connections/Identity/database.json
custom-pages/database-connections/Identity/get_user.js
custom-pages/database-connections/Identity/login.js
custom-pages/rules-configs/audience.json
custom-pages/rules-configs/client_secret.json
custom-pages/rules-configs/gettokenpath.json
custom-pages/rules/If user logged in first time and with AD or Google then create or update account in Identity.js
scripts/hooks/post-create-user.js

https://nicedigital.atlassian.net/browse/IDAM-246

IDAM-246 Synchronise db with rules

---

custom-pages/database-connections/Identity/database.json
custom-pages/database-connections/Identity/login.js
custom-pages/rules-configs/client_id.json
custom-pages/rules/If user logged in first time and with AD or Google then create or update account in Identity.js
custom-pages/universal-login/public/confirmsuccess.html
custom-pages/universal-login/src/components/Login/Login.js
custom-pages/universal-login/src/components/Nav/Nav.js

https://nicedigital.atlassian.net/browse/IDAM-304

IDAM-304 Sign in with NICE accounts migration fix

---

custom-pages/resource-servers/Identity API.json

updating variable in the json to save adding more octo variables.

IDAM-121 Enabling offline access (refresh tokens)

---

custom-pages/universal-login/src/components/Register/Register.js
custom-pages/universal-login/src/components/Register/__tests__/Register.test.js
custom-pages/universal-login/src/services/AuthApi.js
scripts/hooks/post-create-user.js

https://nicedigital.atlassian.net/browse/IDAM-328

IDAM-328 Fix registration error

---

custom-pages/universal-login/src/components/Register/Register.js

https://nicedigital.atlassian.net/browse/IDAM-351

IDAM-317 Registration error messages

---

custom-pages/universal-login/src/components/Register/Register.js

https://nicedigital.atlassian.net/browse/IDAM-341

IDAM-341 Registration warning message

---

custom-pages/universal-login/src/components/Register/Register.scss

https://nicedigital.atlassian.net/browse/IDAM-310

IDAM-310 Highlight validation messages

---

custom-pages/rules/If user logged in first time and with AD or Google then create or update account in Identity.js

https://nicedigital.atlassian.net/browse/IDAM-375

IDAM-375 Updating rule to force account creation when logging in via AD

---

custom-pages/universal-login/src/services/constants.js

https://nicedigital.atlassian.net/browse/EC-838

EC-838 Renaming API endpoint

---

custom-pages/universal-login/package-lock.json
custom-pages/universal-login/src/components/ForgotPassword/ForgotPassword.js
custom-pages/universal-login/src/components/Login/Login.js
custom-pages/universal-login/src/components/Login/__tests__/Login.test.js
custom-pages/universal-login/src/components/Register/Register.js
custom-pages/universal-login/src/components/ResetPassword/ResetPassword.js
custom-pages/universal-login/src/helpers/__tests__/validateLoginFields.test.js
custom-pages/universal-login/src/helpers/__tests__/validateRegisterFields.test.js
custom-pages/universal-login/src/helpers/getFirstErrorElement.js
custom-pages/universal-login/src/helpers/index.js
custom-pages/universal-login/src/helpers/isDomainInUsername.js
custom-pages/universal-login/src/helpers/scrollToMyRef.js
custom-pages/universal-login/src/helpers/validateLoginFields.js
custom-pages/universal-login/src/helpers/validateRegisterFields.js

https://nicedigital.atlassian.net/browse/IDAM-384
https://nicedigital.atlassian.net/browse/IDAM-385

IDAM-384 Register validation + IDAM-385 Login validation

---

custom-pages/rules/If user logged in first time and with AD or Google then create or update account in Identity.js

https://nicedigital.atlassian.net/browse/IDAM-406

IDAM-406 Machine to Machine token usage restriction

---

custom-pages/connections/nice-waad.json
custom-pages/tenant.json

https://nicedigital.atlassian.net/browse/IDAM-421

IDAM-421 Updated AD email setting

---

custom-pages/clients/Tagging.json
custom-pages/clients/Task Scheduler.json
custom-pages/grants/Tagging.json
custom-pages/grants/Task Scheduler.json

https://nicedigital.atlassian.net/browse/ARMS-121

ARMS-121 Adding support for ARMS

---

custom-pages/emails/src/verify_email.html

https://nicedigital.atlassian.net/browse/IDAM-146

IDAM-146 Updating the verification email template

---

custom-pages/clients/Publications API.json
custom-pages/clients/Publications.json
custom-pages/grants/Publications API.json
custom-pages/grants/Publications.json
custom-pages/resource-servers/Publications API.json

https://nicedigital.atlassian.net/browse/IDAM-478

IDAM-478 Add publications API config

---

custom-pages/universal-login/package-lock.json
custom-pages/universal-login/package.json
custom-pages/universal-login/public/confirmsuccess.html

IDAM-482 Mega nav changes

---

custom-pages/universal-login/public/confirmsuccess.html

https://nicedigital.atlassian.net/browse/IDAM-536

IDAM-536 Extra letter displaying on the header and footer

---

custom-pages/actions/Initial AD Login creates account in Identity.json
custom-pages/actions/Initial AD login Creates Account in Identity/code.js
custom-pages/grants/OctopusDeploy-HostedPages.json
custom-pages/rules/If user logged in first time and with AD or Google then create or update account in Identity.json
custom-pages/triggers/triggers.json

https://nicedigital.atlassian.net/browse/IDAM-611

IDAM-611 Convert AD Account Creation Rule to Action

---

custom-pages/universal-login/src/components/Register/Register.js
custom-pages/universal-login/src/components/ResetPassword/ResetPassword.js

IDAM-629 Fix Grammar For Update Minimum Length For Passwords
